#服务器端口
server:
  port: 8082
#spring配置
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ieiltps?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    name: defaultDataSource
    # 连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**
#mybatis-plus配置
mybatis-plus:
  configuration:
    #开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启控制台 SQL 日志打印
    map-underscore-to-camel-case: true